name: "Installation Test"
author: "Graycore"
description: " A Github Action that tests the installability of a Magento Package"

inputs:
  php_version: 
    required: true
    default: "8.1"
    description: "PHP Version to use"

  composer_cache_key:
    required: false
    default: '__graycore'
    description: A key to version the composer cache. Can be incremented if you need to bust the cache.
  
  composer_version: 
    required: true
    default: "2"
    description: "The version of composer to use"

  use_local_source:
    required: false
    default: "true"
    description: "Whether or not you want to test your local package or not."

  source_folder:
    required: true
    default: $GITHUB_WORKSPACE
    description: "The source folder of the package"

  package_name:
    required: true
    description: "The name of the package"

  magento_directory:
    required: true
    default: "../magento2"
    description: "The folder where Magento will be installed"

  magento_version:
    required: true
    default: "magento/project-community-edition"
    description: "The version of Magento to test against"
    
  magento_repository:
    required: true
    default: "https://mirror.mage-os.org/"
    description: "Where to install Magento from"
  
  composer_auth:
    required: false
    description: "Composer Authentication Credentials"

runs:
  using: "composite"
  steps:
    - name: Set PHP Version
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php_version }}
        tools: composer:v${{ inputs.composer_version }}

    - run: composer create-project --repository-url="${{ inputs.magento_repository }}" "${{ inputs.magento_version }}" ${{ inputs.magento_directory }} --no-install
      shell: bash
      env:
        COMPOSER_AUTH: ${{ inputs.composer_auth }}
      name: Create Magento ${{ inputs.magento_version }} Project 

    - uses: ./init-magento
      name: "Initialize Magento"
      with: 
        magento_directory: ${{ inputs.magento_directory }}
        composer_cache_key: ${{ inputs.composer_cache_key }}

    - run: composer config repositories.local path ${{ inputs.source_folder }}
      name: Add Github Repo for Testing
      working-directory:  ${{ inputs.magento_directory }}
      shell: bash
      if: ${{ inputs.use_local_source == 'true' }}
    
    - run: composer require ${{ inputs.package_name }} "@dev" --no-update && composer install
      name: Require and attempt install
      working-directory:  ${{ inputs.magento_directory }}
      shell: bash
      env:
        COMPOSER_AUTH: ${{ inputs.composer_auth }}

branding:
  icon: "code"
  color: "green"
